# Generated by Django 2.2.5 on 2019-09-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='imgs',
            field=models.FileField(blank=True, null=True, upload_to='minuta/'),
        ),
    ]
