# Generated by Django 2.2.5 on 2019-09-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0002_page_imgs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgs', models.FileField(blank=True, null=True, upload_to='minuta/')),
            ],
        ),
        migrations.RemoveField(
            model_name='page',
            name='imgs',
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
