# Generated by Django 2.2.5 on 2019-09-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0003_auto_20190916_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgs',
            name='imgs',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
